# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6b176a60abb71be57d3add35843c586162bbc430884b7f3f73215cbae73632cb87b9b717a124aec5b4860ffa6dedd6ca30bb00b9d3d3ec93a490cc7073dfb2

test:
  secret_key_base: 5d8fc943175eea38ca035e9003cbf56ad6d5486523c94c4436fa3c1b83e4fad8018c06c5cfe3f35f1a4e8266082d8da1ea40aa41140bc7f4e453151b5823b30e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
